CREATE TABLE productos (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(150) NOT NULL,
	descripcion TEXT,
	precio DECIMAL(10, 2) NOT NULL,
	stock INT UNSIGNED NOT NULL DEFAULT 0,
	categoria VARCHAR(100),
	imagen_url VARCHAR(255),
	creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT chk_productos_precio CHECK (precio >= 0)
);
